language: R
cache:
  packages: true
  directories: ["book/tex", "_figures", "_cache"]

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - optipng
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

before_script:
  - tlmgr install index

script:
  - make clean # blow away checked in artifacts
  - make
