language: R
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.3.1

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - optipng
      - ghostscript
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - libnode-dev
      - libjq-dev
      - libprotobuf-dev
      - protobuf-compiler

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- nvm install stable
- npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true
