language: R
cache:
  packages: true
  directories:
    - _bookdown_files  

pandoc_version: 2.3.1

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - optipng
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

before_script:
  - tlmgr install index

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'
