language: R
cache:
  packages: true
  directories: ["book/tex", "_figures", "_cache"]

addons:
  apt:
    packages:
      - optipng
      - libudunits2-dev

before_script:
  - tlmgr install index

script:
  - make clean # blow away checked in artifacts
  - make
